# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Inupiaq spellchecker"
ik = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Inupiaq, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ik = "TRANSLATE: A spellchecker for Inupiaq, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ik"

[windows]
system_product_code = "{3900497A-5887-40E1-9CBF-5F13B7A920B1}_is1"
legacy_product_codes = [
    { value = "F984A8A2-31EA-4A99-89FE-03D0DBF07651", kind = "nsis" },
    { value = "F90F9C8C-9DD1-4EB3-A66E-DE4334C19CFA", kind = "nsis" }
]

[package.speller]
name = "Inupiaq"
version = "0.1.1"

[package.grammar]
name = "Inupiaq"
version = "0.1.0"

[package.tts-text-proc]
name = "Inupiaq"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
