template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "inup1234"
__REPO__ = "lang-ipk"
__UND2C__ = "ik"
__UNDEFINED__ = "Inupiaq"
__UND__ = "ipk"
